[package]
edition = '2021'
name = 'memtest_vulkan_build'
version = '0.0.0'

[dependencies]
quote = '1.0'
syn = '2.0'
naga = { version = "0.19", features = ["wgsl-in", "spv-out"] }


[lib]
proc-macro = true
